line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "D212",
    "D203",
    "D400",
    "D415",
    "PYI019",
    "INP001",
    "D212",
    "PLR0913",
    "COM812",
]

[format]
quote-style = "double"