exclude = ["*/migrations/*"]

line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "D212",
    "D203",
    "D400",
    "D415",
    "D212",
    "PLR0913",
    "COM812",
    "TRY301",
    "RUF001",
    "S301",
    "C901",
    "PLR0912",
    "PLR0915",
]

[format]
quote-style = "double"