line-length = 120
indent-width = 4
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "D212",
    "D203",
    "D400",
    "D415",
    "D212",
    "PLR0913",
    "COM812",
    "TRY301",
    "RUF001",
    "S301",
    "C901",
    "PLR0912",
    "PLR0915",
]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "ANN201", "ANN001", "ANN002", "SLF001", "ANN401", "PLR2004", "SIM117", "PT011", "B017", "TC001"]

[format]
quote-style = "double"
