"""initial_schema

Revision ID: b29bbdf86ff8
Revises: 
Create Date: 2026-04-25 14:40:46.662328+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b29bbdf86ff8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='checklists'
    )
    op.create_index(op.f('ix_checklists_departments_id'), 'departments', ['id'], unique=False, schema='checklists')
    op.create_index(op.f('ix_checklists_departments_name'), 'departments', ['name'], unique=True, schema='checklists')
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Enum('JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', name='employeelevel', inherit_schema=True), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('task_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_assignee_role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'DEPRECATED', name='templatestatus', inherit_schema=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['checklists.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='checklists'
    )
    op.create_index(op.f('ix_checklists_templates_id'), 'templates', ['id'], unique=False, schema='checklists')
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='status', inherit_schema=True), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklists.templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='checklists'
    )
    op.create_index(op.f('ix_checklists_checklists_employee_id'), 'checklists', ['employee_id'], unique=False, schema='checklists')
    op.create_index(op.f('ix_checklists_checklists_id'), 'checklists', ['id'], unique=False, schema='checklists')
    op.create_index(op.f('ix_checklists_checklists_user_id'), 'checklists', ['user_id'], unique=False, schema='checklists')
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('DOCUMENTATION', 'INTRODUCTION', 'TECHNICAL', 'TRAINING', 'MEETING', 'PAPERWORK', 'SECURITY', 'HR', 'OTHER', name='taskcategory', inherit_schema=True), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('due_days', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assignee_role', sa.String(length=50), nullable=True),
    sa.Column('auto_assign', sa.Boolean(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklists.templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='checklists'
    )
    op.create_index(op.f('ix_checklists_task_templates_id'), 'task_templates', ['id'], unique=False, schema='checklists')
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('template_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('DOCUMENTATION', 'INTRODUCTION', 'TECHNICAL', 'TRAINING', 'MEETING', 'PAPERWORK', 'SECURITY', 'HR', 'OTHER', name='taskcategory', inherit_schema=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='status', inherit_schema=True), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('assignee_role', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.checklists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='checklists'
    )
    op.create_index(op.f('ix_checklists_tasks_id'), 'tasks', ['id'], unique=False, schema='checklists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklists_tasks_id'), table_name='tasks', schema='checklists')
    op.drop_table('tasks', schema='checklists')
    op.drop_index(op.f('ix_checklists_task_templates_id'), table_name='task_templates', schema='checklists')
    op.drop_table('task_templates', schema='checklists')
    op.drop_index(op.f('ix_checklists_checklists_user_id'), table_name='checklists', schema='checklists')
    op.drop_index(op.f('ix_checklists_checklists_id'), table_name='checklists', schema='checklists')
    op.drop_index(op.f('ix_checklists_checklists_employee_id'), table_name='checklists', schema='checklists')
    op.drop_table('checklists', schema='checklists')
    op.drop_index(op.f('ix_checklists_templates_id'), table_name='templates', schema='checklists')
    op.drop_table('templates', schema='checklists')
    op.drop_index(op.f('ix_checklists_departments_name'), table_name='departments', schema='checklists')
    op.drop_index(op.f('ix_checklists_departments_id'), table_name='departments', schema='checklists')
    op.drop_table('departments', schema='checklists')
    # ### end Alembic commands ###
